name: Desktop Issue
description: Desktop Issue related to Firmware/Software/Drivers
title: "[Desktop] "
labels: ["Desktop"]
body:
  - type: dropdown
    id: sku
    attributes:
      label: System Model or SKU
      options:
        - Framework Desktop (AMD Ryzen™ AI Max 300 Series)
    validations:
      required: true
  - type: input
    id: bios-version
    attributes:
      label: BIOS Version
      description: >-
        Windows: open a command terminal as administrator and run
        `wmic bios get SMBIOSBIOSVERSION`.
        Linux: open a terminal and run `sudo dmidecode --string bios-version`.
      placeholder: e.g. 3.03
    validations:
      required: true
  - type: textarea
    id: diy-info
    attributes:
      label: DIY Edition Information
      description: >-
        If you are experiencing an issue on a DIY system, please also fill out
        the storage devices you are using.
      value: |
        Storage: [Manufacturer and SKU]
  - type: textarea
    id: port-peripheral
    attributes:
      label: Port/Peripheral Information
      description: >-
        If you are experiencing an issue with a peripheral or an expansion
        card/port, please fill out the peripheral vendor and name, the port it
        was connected to (see
        [Desktop port numbering](https://knowledgebase.frame.work/en_us/expansion-card-functionality-on-framework-desktop-amd-ryzen-ai-max-300-series-HyhiaJYVxl)),
        and the device or expansion card attached to the **adjacent port**.
      value: |
        Peripheral vendor and name:
        1. [Fill in device / expansion card]
        2. [Fill in device / expansion card]
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps To Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: >-
        If applicable, add screenshots to help explain your problem
        (drag and drop images into this field).
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g. Windows 11 25H2, Ubuntu 26.04
    validations:
      required: true
  - type: input
    id: kernel
    attributes:
      label: Linux Kernel Version
      description: If using Linux, the output of `uname -a`.
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
